### ISSUE TITLE
can i ask what version is your numpy？

### ISSUE THREAD

**Issue by ZevineXu** [snu-mllab/DiscreteBlockBayesAttack#3]
When I run the code from this repo, I always get numpy related issues and other conflicts. So can i ask what version is you numpy? Or give me a requirements.txt.Thank you.

**Comment by badeok0716** [comment]
Hi ZevineXu,

Thank you for pointing out version issues in this repo!
I updated requirements.txt files at the recent commits. 
- [snu-mllab/DiscreteBlockBayesAttack/protein_attack/requirements.txt: ad7c85e2e2b7ecb69b7996d250eed387886703b9](https://github.com/snu-mllab/DiscreteBlockBayesAttack/blob/main/protein_attack/requirements.txt)
- [badeok0716/TextAttack/requirements.txt: b572c80c4c45a6cc924e4145d1a7d04a0d9adec7](https://github.com/badeok0716/TextAttackDBBA/blob/b572c80c4c45a6cc924e4145d1a7d04a0d9adec7/requirements.txt)

Please follow the instructions in the README.md files of the recent commits.
